import { Component, Input, Output, EventEmitter, signal, ChangeDetectionStrategy, inject } from '@angular/core';
import { DatePipe } from '@angular/common';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';
import { marked } from 'marked';
import DOMPurify from 'dompurify';
import { Postmortem, PostmortemStatus } from '../../../core/models/postmortem.model';

@Component({
  selector: 'app-incident-postmortem',
  standalone: true,
  imports: [DatePipe],
  templateUrl: './incident-postmortem.html',
  styleUrl: './incident-postmortem.scss',
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class IncidentPostmortem {

  @Input({ required: true }) postmortem!: Postmortem;
  @Input() loading = false;

  /**
   * Matches the exact role requirement on the backend's own
   * PostmortemController (@PreAuthorize("hasRole('RESPONDER') or
   * hasRole('ADMIN')") on both updateContent and markReviewed) — hides
   * the Edit/Mark as Reviewed actions for a role that would get a 403
   * from the backend anyway, the same way incident-detail's own
   * Assignment section is hidden via canManageIncidents.
   */
  @Input() canManage = false;

  /**
   * This component stays a "dumb", presentation-only component — it has
   * no IncidentService dependency and makes no HTTP calls itself,
   * matching IncidentAudit's own pattern and the rest of
   * incident-detail's architecture (the parent owns every mutation
   * through IncidentService; children only emit that a mutation was
   * requested). save/markReviewed are handled by IncidentDetail, which
   * calls IncidentService.updatePostmortemContent()/
   * markPostmortemReviewed() and updates the postmortem signal those
   * calls flow back through.
   */
  @Output() save = new EventEmitter<string>();
  @Output() markReviewed = new EventEmitter<void>();

  private readonly sanitizer = inject(DomSanitizer);

  readonly editing = signal(false);
  readonly draftContent = signal('');

  startEdit(): void {
    this.draftContent.set(this.postmortem.content ?? '');
    this.editing.set(true);
  }

  cancelEdit(): void {
    this.editing.set(false);
  }

  onSave(): void {
    this.save.emit(this.draftContent());
    this.editing.set(false);
  }

  onMarkReviewed(): void {
    this.markReviewed.emit();
  }

  /**
   * Fixed: this component previously read seven separate section fields
   * (summary, timeline, rootCause, impact, resolution, actionItems,
   * lessonsLearned) that PostmortemDto has never sent — see
   * postmortem.model.ts's own comment for the full account. The backend
   * has always stored the AI-generated report as a single markdown block
   * in `content`; this renders that block as HTML.
   *
   * marked.parse() does not sanitize its output — confirmed directly
   * against marked's own documentation, not assumed — so its result is
   * passed through DOMPurify before being marked safe for [innerHTML].
   * This matters here specifically because `content` is generated by
   * Gemini from a prompt built partly from incident data (title,
   * description) that can originate from an external, potentially
   * untrusted alerting system via ingestion-service — if Gemini ever
   * echoes attacker-controlled input back verbatim, an unsanitized
   * render would be a stored XSS vector for whoever next opens this
   * incident's postmortem.
   */
  get renderedContent(): SafeHtml | null {
    if (!this.postmortem.content) {
      return null;
    }

    const rawHtml = marked.parse(this.postmortem.content) as string;
    const safeHtml = DOMPurify.sanitize(rawHtml);
    return this.sanitizer.bypassSecurityTrustHtml(safeHtml);
  }

  getStatusLabel(status: PostmortemStatus): string {
    const labels: Record<PostmortemStatus, string> = {
      'GENERATING':         '⏳ Generating...',
      'DRAFT':              '📝 Draft',
      'REVIEWED':           '✅ Reviewed',
      'FAILED':             '❌ Failed — retrying',
      // Fixed: PERMANENTLY_FAILED was previously absent from this map
      // (and from the PostmortemStatus union type itself) — for a
      // postmortem in that state, labels[status] returned undefined,
      // rendering as blank/"undefined" in the status badge instead of
      // any indication of what was actually wrong.
      'PERMANENTLY_FAILED': '🛑 Failed — needs review'
    };
    return labels[status];
  }

  getStatusClass(status: PostmortemStatus): string {
    const classes: Record<PostmortemStatus, string> = {
      'GENERATING':         'postmortem__status--generating',
      'DRAFT':              'postmortem__status--draft',
      'REVIEWED':           'postmortem__status--reviewed',
      'FAILED':             'postmortem__status--failed',
      'PERMANENTLY_FAILED': 'postmortem__status--failed'
    };
    return classes[status];
  }
}